version: "3"
services:
  db:
    image: mysql:8.0.21
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "23306:3306"
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'root_pass'
      MYSQL_DATABASE: 'test'
    volumes:
      - db_volume:/var/lib/mysql
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app:cached
#    environment:
    ports:
      - "3001:3001"
    depends_on:
      - db
volumes:
  db_volume:
