version: "3"
services:
  db:
    image: mysql:5.6.34
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "13306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - mysql_volume:/var/lib/mysql
    logging:
      options:
        max-size: 32m
        max-file: "5"
  web:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/go/src/app:cached
#    environment:
    ports:
      - "3001:3001"
    depends_on:
      - db
volumes:
  mysql_volume:
